import type { Metadata } from "next";
import { Farsan, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const font = Poppins({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Cratonik | Let's get improved...",
	description: "Generated by create next app",
};

const scroll = true;

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					font.className,
					"transition-all bg-white",
					"min-h-[100vh]",
					scroll ? "pt-[60px] pl-[30px] pr-[30px]" : ""
				)}
			>
				{children}
			</body>
		</html>
	);
}
